# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: cimg/golang:1.21
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/project
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go mod tidy
      - run: go mod vendor
      - run: go test -v ./...
