version: 2.1
jobs:
  build:
    docker:
      - image: cimg/golang:1.21
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go mod vendor
      - run: go get -v -t -d ./...
      - run: go test -v ./...
